### ISSUE TITLE
How could users add new papers to the list?

### ISSUE THREAD

**Issue by BAILOOL** [hollobit/All-About-the-GAN#5]
Could you please provide a guide on how we can contribute to extend the list of papers?

**Comment by hollobit** [comment]
If you want to extend the list of papers, please let me know the list of papers using this issue. 

In another way, If you want to extend the list of papers on your own list, you can make your own extended list by fork this repository.

**Comment by BAILOOL** [comment]
@hollobit, thank you for your response. Actually, what I had in mind is that this repository is not synchronized with the [medical gan repository](https://github.com/xinario/awesome-gan-for-medical-imaging/) that this project includes.
